<?php

return array(
	'aero' => array(),
	'asia' => array(),
	'biz' => array(),
	'cat' => array(),
	'com' => array(),
	'coop' => array(),
	'edu' => array(),
	'gov' => array(),
	'info' => array(),
	'int' => array(),
	'jobs' => array(),
	'mil' => array(),
	'mobi' => array(),
	'museum' => array(),
	'name' => array(),
	'net' => array(),
	'org' => array(),
	'pro' => array(),
	'tel' => array(),
	'travel' => array(),
	'xxx' => array(),
	'ac' => array(),
	'ad' => array(),
	'ae' => array(),
	'af' => array(),
	'ag' => array(),
	'ai' => array(),
	'al' => array(),
	'am' => array(),
	'an' => array(),
	'ao' => array(),
	'aq' => array(),
	'ar' => array(),
	'as' => array(),
	'at' => array(),
	'au' => array(),
	'aw' => array(),
	'az' => array(),
	'ax' => array(),
	'ba' => array(),
	'bb' => array(),
	'bd' => array(),
	'be' => array(),
	'bf' => array(),
	'bg' => array(),
	'bh' => array(),
	'bi' => array(),
	'bj' => array(),
	'bm' => array(),
	'bn' => array(),
	'bo' => array(),
	'br' => array(),
	'bs' => array(),
	'bt' => array(),
	'bv' => array(),
	'bw' => array(),
	'by' => array(),
	'bz' => array(),
	'ca' => array(),
	'cc' => array(),
	'cd' => array(),
	'cf' => array(),
	'cg' => array(),
	'ch' => array(),
	'ci' => array(),
	'ck' => array(),
	'cl' => array(),
	'cm' => array(),
	'cn' => array(
		'com',
		'net',
		'org',
		'edu',
		'gov',
		'ac',
		'bj',
		'sh',
		'cq',
		'he',
		'sx',
		'nm',
		'ln',
		'jl',
		'hl',
		'js',
		'zj',
		'ah',
		'fj',
		'jx',
		'sd',
		'ha',
		'hb',
		'hn',
		'gd',
		'gx',
		'hi',
		'sc',
		'gz',
		'yn',
		'xz',
		'sn',
		'gs',
		'qh',
		'nx',
		'xj',
		'tj',
		'tw',
		'hk',
		'mo',
	),
	'co' => array(),
	'cr' => array(),
	'cs' => array(),
	'cu' => array(),
	'cv' => array(),
	'cx' => array(),
	'cy' => array(),
	'cz' => array(),
	'de' => array(),
	'dj' => array(),
	'dk' => array(),
	'dm' => array(),
	'do' => array(),
	'dz' => array(),
	'ec' => array(),
	'ee' => array(),
	'eg' => array(),
	'eh' => array(),
	'er' => array(),
	'es' => array(),
	'et' => array(),
	'eu' => array(),
	'fi' => array(),
	'fj' => array(),
	'fk' => array(),
	'fm' => array(),
	'fo' => array(),
	'fr' => array(),
	'ga' => array(),
	'gb' => array(),
	'gd' => array(),
	'ge' => array(),
	'gf' => array(),
	'gg' => array(),
	'gh' => array(),
	'gi' => array(),
	'gl' => array(),
	'gm' => array(),
	'gn' => array(),
	'gp' => array(),
	'gq' => array(),
	'gr' => array(),
	'gs' => array(),
	'gt' => array(),
	'gu' => array(),
	'gw' => array(),
	'gy' => array(),
	'hk' => array(
		'com'
	),
	'hm' => array(),
	'hn' => array(),
	'hr' => array(),
	'ht' => array(),
	'hu' => array(),
	'id' => array(),
	'ie' => array(),
	'il' => array(),
	'im' => array(),
	'in' => array(),
	'io' => array(),
	'iq' => array(),
	'ir' => array(),
	'is' => array(),
	'it' => array(),
	'je' => array(),
	'jm' => array(),
	'jo' => array(),
	'jp' => array(
		'co'
	),
	'ke' => array(),
	'kg' => array(),
	'kh' => array(),
	'ki' => array(),
	'km' => array(),
	'kn' => array(),
	'kp' => array(),
	'kr' => array(
		'co'
	),
	'kw' => array(),
	'ky' => array(),
	'kz' => array(),
	'la' => array(),
	'lb' => array(),
	'lc' => array(),
	'li' => array(),
	'lk' => array(),
	'lr' => array(),
	'ls' => array(),
	'lt' => array(),
	'lu' => array(),
	'lv' => array(),
	'ly' => array(),
	'ma' => array(),
	'mc' => array(),
	'md' => array(),
	'me' => array(),
	'mg' => array(),
	'mh' => array(),
	'mk' => array(),
	'ml' => array(),
	'mm' => array(),
	'mn' => array(),
	'mo' => array(),
	'mp' => array(),
	'mq' => array(),
	'mr' => array(),
	'ms' => array(),
	'mt' => array(),
	'mu' => array(),
	'mv' => array(),
	'mw' => array(),
	'mx' => array(),
	'my' => array(),
	'mz' => array(),
	'na' => array(),
	'nc' => array(),
	'ne' => array(),
	'nf' => array(),
	'ng' => array(),
	'ni' => array(),
	'nl' => array(),
	'no' => array(),
	'np' => array(),
	'nr' => array(),
	'nu' => array(),
	'nz' => array(),
	'om' => array(),
	'pa' => array(),
	'pe' => array(),
	'pf' => array(),
	'pg' => array(),
	'ph' => array(),
	'pk' => array(),
	'pl' => array(),
	'pm' => array(),
	'pn' => array(),
	'pr' => array(),
	'ps' => array(),
	'pt' => array(),
	'pw' => array(),
	'py' => array(),
	'qa' => array(),
	're' => array(),
	'ro' => array(),
	'ru' => array(
		'com'
	),
	'rw' => array(),
	'sa' => array(),
	'sb' => array(),
	'sc' => array(),
	'sd' => array(),
	'se' => array(),
	'sg' => array(),
	'sh' => array(),
	'si' => array(),
	'sj' => array(),
	'sk' => array(),
	'sl' => array(),
	'sm' => array(),
	'sn' => array(),
	'so' => array(),
	'sr' => array(),
	'st' => array(),
	'sv' => array(),
	'sy' => array(),
	'sz' => array(),
	'tc' => array(),
	'td' => array(),
	'tf' => array(),
	'tg' => array(),
	'th' => array(),
	'tj' => array(),
	'tk' => array(),
	'tl' => array(),
	'tm' => array(),
	'tn' => array(),
	'to' => array(),
	'tp' => array(),
	'tr' => array(),
	'tt' => array(),
	'tv' => array(),
	'tw' => array(
		'com'
	),
	'tz' => array(),
	'ua' => array(),
	'ug' => array(),
	'uk' => array(
		'co'
	),
	'um' => array(),
	'us' => array(),
	'uy' => array(),
	'uz' => array(),
	'va' => array(),
	'vc' => array(),
	've' => array(),
	'vg' => array(),
	'vi' => array(),
	'vn' => array(),
	'vu' => array(),
	'wf' => array(),
	'ws' => array(),
	'ye' => array(),
	'yt' => array(),
	'yu' => array(),
	'za' => array(),
	'zm' => array(),
	'zw' => array()
);